### ISSUE TITLE
You are not setting the playing 

### ISSUE THREAD

**Issue by bdougie** [imdoingotherthings/bloc-jams-angular#7]
https://github.com/imdoingotherthings/bloc-jams-angular/blob/directivesPt1/app/scripts/services/SongPlayer.js#L72

You need to pass a song on line 72
```js
if (SongPlayer.currentSong !== song) {
  setSong(song);
  playSong();
} 
```

Needs to be 
```js
playSong(song)
```

**Comment by bdougie** [comment]
You are also not setting the currentSong on the SongPlayer.

You should be doing the following
```js
SongPlayer.currentSong = song
```

Not this https://github.com/imdoingotherthings/bloc-jams-angular/blob/master/app/scripts/services/SongPlayer.js#L46

currentSong is never defined in SongPlayer.js

**Comment by bdougie** [comment]
Fixing the above two issues will unblock you ;)

**Comment by imdoingotherthings** [comment]
So I added the code that you shared with me to fix, but I'm getting an error with the `isPaused()` function. 

![screen shot 2016-12-01 at 3 20 29 pm](https://cloud.githubusercontent.com/assets/20527548/20816945/c828f6bc-b7d9-11e6-82a5-030e48a89e6d.png)

On another note the player bar still isnt being displayed. 

Link to the latest submission of the branch I'm working on is here: [https://github.com/imdoingotherthings/bloc-jams-angular/tree/directivesPt1](url)

**Comment by bdougie** [comment]
The isPaused function is not the problem. Its what is calling the isPaused function, That object is null. Make sure when you console.log, you have a current song playing being set.

**Comment by imdoingotherthings** [comment]
Okay so I can see where the object is coming from and I’m trying to access it directly from the `Fixtures` file which has all of our albums data. But when I console.log it, the object only stays in one state and doesnt switch to a different song title. As you can tell by this image the object is title RED but after I play a different song the title does not change.

![object title red](https://cloud.githubusercontent.com/assets/20527548/20823288/a4821b0c-b807-11e6-85f1-89324908a1e9.png)


So my code at the moment inside of the `player_bar.html` file is this.... 
``` <h2 class="song-name">{{ playerBar.songPlayer.songs }}</h2> ``` . 

So I’m using this approach to firstly use the `PlayerBarCtrl` controller. Then we have `songPlayer` (the code is `this.songPlayer = SongPlayer;`)  which contains the `SongPlayer.js` file that has all of our updates and functionality. Finally I use `.songs` because we have access to `Fixtures.js` since we passed it in as an argument in the function `SongPlayer` like so...
```
function SongPlayer (Fixtures) { 
  ....
}
```
So then fixtures contains `songs` which has our MP3 files that we are trying to access. 

All in all I'm doing this to figure out how to update the player bar.

**Comment by bdougie** [comment]
See my PR #8, You were close and on the right track, just overlooked some things that was preventing the current song from being selected. The latest error message I saw was complaining that `song` was not defined. 

If you merge #8, you should be able to see the song name and then proceed to get the data from `songPlayer.currentSong` to display `duration` and `album`
